### PR TITLE
ZMS-596 TestTrashImapMessage test updates

### PR DESCRIPTION
**Pull request by tmclane**

### CODE REVIEW

**Comment by tmclane** [comment]
I did notice if I run the test multiple times in a row sometimes I get a 'PROXY_ERROR' exception.  So we may have some transitory connection issues in the SOAP backend.

**Comment by grishick** [comment]
@tmclane which code path causes PROXY_ERROR? Not sure it makes sense to be sending SOAP requests from one server to another via NGINX.

**Comment by tmclane** [comment]
@grishick I am unsure actually.  I am just running the test using the 'zmsoap -z RunUnitTestsRequest/test=com.zimbra.qa.unittest.TestTrashImapMessage' .

With the following 'occasional' output:

```
<RunUnitTestsResponse numFailed="1" numSkipped="0" numExecuted="1" xmlns="urn:zimbraAdmin">
  <results>
    <failure name="testTrashImapMessage" class="com.zimbra.qa.unittest.TestTrashImapMessage" execSeconds="0.22">error while proxying request to target server: zcs-development-two.dev</failure>
  </results>
</RunUnitTestsResponse>
```

The mailbox.log file shows:

```
2017-04-04 09:38:29,013 ERROR [qtp895947612-104:https:https://localhost:7071/service/admin/soap/RunUnitTestsRequest] [name=zimbra;ua=zmsoap;] test - Test com.zimbra.qa.unittest.TestTrashImapMessage.testTrashImapMessage failed.
com.zimbra.common.soap.SoapFaultException: error while proxying request to target server: zcs-development-two.dev
ExceptionId:qtp895947612-93:1491316709010:a4b8d0bebb36475e
Code:service.PROXY_ERROR
	at com.zimbra.common.soap.Soap12Protocol.soapFault(Soap12Protocol.java:90)
	at com.zimbra.common.soap.SoapTransport.extractBodyElement(SoapTransport.java:366)
	at com.zimbra.common.soap.SoapTransport.parseSoapResponse(SoapTransport.java:339)
	at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:267)
```

Note: The log snippet is truncated since it is lengthy.

**Comment by grishick** [comment]
so this is not going through NGINX. This is SoapHttpTransport getting something other than 200 or 500 from "zcs-development-two.dev". There is probably another stack trace on "zcs-development-two.dev" in mailbox.log or zmmailboxd.out that explains why it is responding with non 200 and non 500 code.

**Comment by tmclane** [comment]
Just double checked and there doesn't seem to be any error condition log statements on zcs-development-two at all actually in either file.

**Comment by grishick** [comment]
maybe if you delete that "deleteFolder" call things will run smoother. it's not needed anyway ;)

**Comment by tmclane** [comment]
I was wondering about that.  Is the 'deleteDataSource' call necessary ? 
I suspect it isn't if the accounts are being deleted anyhow.

**Comment by fatkudu** [comment]
I think the deleteDataSource is redundant.  We don't even check whether it worked, which might be valuable as a test case but hopefully that is covered elsewhere.

**Comment by tmclane** [comment]
This has been updated to pull the unnecessary code.

**Pull request merged**
