### PR TITLE
ZBUG-2835 : Changing debug level to info from debug for syslog

### PR DESCRIPTION
**Pull request by abhishekdeshmukh2209**

### CODE REVIEW

**Review by silentsakky — APPROVED** [review]

**Review by deepakzimb — APPROVED** [review]

**Review by umagmrit — APPROVED** [review]

**Review by dasiyogesh — APPROVED** [review]

**Review by zimsuchitgupta — APPROVED** [review]

**Review by desouzas — APPROVED** [review]
Sign CLA

**Review by ghen2 — COMMENTED** [review]
There's an error on the line below: %%uncomment instead of %%comment, it breaks the config if you're not using syslog:

system failure: org.apache.logging.log4j.core.config.ConfigurationException: No name attribute provided for Logger slogger

no logs are written at all due to this.

**Comment by ghen2** [comment]
> this will happen only if we haven't set zimbraLogHostname. which by default is set to hostname.

`zimbraLogHostname` is not set (empty) by default here.  With this, it generates the following log4j.properties:

```
#logger.slogger.name = zimbra.slogger
#logger.slogger.level=INFO
logger.slogger.level=ERROR
#logger.slogger.additivity = false
#logger.slogger.appenderRef.SLOGGER.ref = sloggerAppender
```
Which is broken because the third line is not commented, but `slogger` is not defined, resulting in no logs at all:

system failure: org.apache.logging.log4j.core.config.ConfigurationException: No name attribute provided for Logger slogger

Either this block should be commented completely, or uncommented completely, not partially like the current code.

Another side effect is that, after fixing this, we now get these "slogger" statistics (mailboxd.csv, ldap,csv etc) in our standard mailbox.log.

**Comment by abhishekdeshmukh2209** [comment]
I agree @ghen2 
the only thing that needs to done for now is that we will have to remove line 211 from log4j.properties.in and do a
zmmailboxdctl restart
we will fix this in next PR

**Comment by ghen2** [comment]
Ah I missed that duplicate, indeed just remove it then.

**Comment by ghen2** [comment]
Perhaps the goal of this construction to log only ERROR level when "slogger" is NOT going to syslog?

**Comment by ghen2** [comment]
Yes indeed, the [old config](https://github.com/Zimbra/zm-mailbox/blob/71c02c95f45c421cbb365d457988c922c8c85dfe/store-conf/conf/log4j.properties.production) (before log4j 2.17 upgrade) looked like:

```
log4j.additivity.zimbra.slogger=FALSE
%%comment VAR:!zimbraLogHostname%%log4j.logger.zimbra.slogger=INFO,SLOGGER
%%uncomment VAR:!zimbraLogHostname%%log4j.logger.zimbra.slogger=ERROR
```

**Comment by abhishekdeshmukh2209** [comment]
@ghen2  
https://github.com/Zimbra/zm-mailbox/pull/1293

**Pull request merged**
