### PR TITLE
Bugfix/zcs 1773

### PR DESCRIPTION
**Pull request by jasonyi-zimbra**
Updated ZimbraPerf.java and ImapDaemon.java to properly intialize ZimbraPerf in ImapDaemon to write out imapd.csv file for ImapDaemon stat collection.

### CODE REVIEW

**Comment by jasonyi-zimbra** [comment]
@grishick 

Hi Greg,

I hope I got this right this time following the git-util's readme's.
I did following steps:

> git flow bugfix start ZCS-1773 feature/imap
  ... made changes ...
> git flow bugfix rebase ZCS-1773
> git push https://github.com/jasonyi-zimbra/zm-mailbox.git +bugfix/ZCS-1773
....made a pull request...

Thanks.

Jason

**Comment by fatkudu** [comment]
@jasonyi-zimbra - you rebased on feature/imap (the correct thing to do).  However, this pull request targets the develop branch (the wrong target branch).  I think you need to target the feature/imap branch in a new pull request.

**Comment by jasonyi-zimbra** [comment]
@fatkudu 

Ok, I didn't catch that.  I think it's good now.  thanks.

Jason

**Comment by chinmay15** [comment]
Is this merged in develop?

**Comment by jasonyi-zimbra** [comment]
Yes.  


----- Original Message -----

**Pull request closed without merging**
