### PR TITLE
ZBUG-2859 Bugzilla 80485 admin login honors zimbraAuthFallbackToLocal

### PR DESCRIPTION
**Pull request by ghost**
ZBUG-2859 Bugzilla 80485 admin login honors zimbraAuthFallbackToLocal

### CODE REVIEW

**Comment by k-kato** [comment]
It was introduced in https://bugzilla.zimbra.com/show_bug.cgi?id=5106
Is there any case that an administrator wants to use a local password even when zimbraAuthFallbackToLocal is FALSE? Don't we need to add ldap attr or localconfig to switch fallback logic for admin account considering backward compatibility?

**Comment by ghost** [comment]
> It was introduced in https://bugzilla.zimbra.com/show_bug.cgi?id=5106 Is there any case that an administrator wants to use a local password even when zimbraAuthFallbackToLocal is FALSE? Don't we need to add ldap attr or localconfig to switch fallback logic for admin account considering backward compatibility?

No I think the reasoning in 5106 is not sensible from a security perspective .

**Review by k-kato — APPROVED** [review]
I see. Then the change LGTM.

**Comment by ghost** [comment]
> I see. Then the change LGTM.

But just in case someone runs into that issue again, I added an instruction here: https://wiki.zimbra.com/wiki/How_To_Create_an_Admin_Account

**Comment by silentsakky** [comment]
Changes moved to https://github.com/Zimbra/zm-mailbox/pull/1597 for merging as this branch was having merge commits.

**Pull request closed without merging**
