### PR TITLE
Fixing wrong sequences of two apostrophe characters in the Italian

### PR DESCRIPTION
**Pull request by zx-fulvio**
localization.

Same sort of fix as in  [this pull request](https://github.com/Zimbra/zm-web-client/pull/99)

### CODE REVIEW

**Comment by zx-fulvio** [comment]
Referenced [here](https://github.com/Zimbra/zm-web-client/pull/99)

**Comment by silentsakky** [comment]
I think this pull request needs a rebase

**Comment by zx-fulvio** [comment]
Rebased as requested!

**Comment by zx-fulvio** [comment]
@silentsakky @mihaipopahtp This I think should be applied/merged before applying the global modifications mentioned in [this pull request](https://github.com/Zimbra/zm-web-client/pull/115).
Just to avoid doubling smart quotes too by mistake :-) .

**Comment by silentsakky** [comment]
Will be fixed as part of https://github.com/Zimbra/zm-mailbox/pull/338

**Pull request closed without merging**
