### PR TITLE
ZCS-1937 shared sub folder support.

### PR DESCRIPTION
**Pull request by fatkudu**
Fix various problems with selecting sub folders.
Also problems fetching from shared folders (both top level and sub folders)

### CODE REVIEW

**Comment by fatkudu** [comment]
Note.  Just gone to the bug to point at this pull request and spotted that Rohit was reporting a problem with STATUS as well.  Just done a quick hack to the tests to try that out.  Remote is still failing for mountpoints :(

**Comment by fatkudu** [comment]
@gordyt which do you mean, SELECT or STATUS?  I'm expecting STATUS to work for both a top level and a subfolder but STATUS is an outstanding problem.

**Comment by gordyt** [comment]
That was a typo.  Have updated the comment.  `STATUS` is failing for the top-level `Manage` folder (that was shared from user 1 to user 2) but working with the `Manage2` (sub-folder of `Manage`) by user 2 as per step 6 in the description.

**Comment by fatkudu** [comment]
@gordyt.  My turn for typos!  This Jira is targeting `SELECT` not `STATUS`.  I've created some sketchy SOAP test cases for STATUS.  I'll create a Jira for that tomorrow and probably start working on it unless there is something obviously more urgent.

**Pull request merged**
