### PR TITLE
Fixed blob store if it's compressed size is equal to uncompressed one

### PR DESCRIPTION
**Pull request by DinoPuller**
There is a bug on blob handling if it's compressed size is equal to uncompressed one.
* Reproduction: 
1. create a primary compressed volume with a threshold of 1 byte (or really small)
2. upload to briefcase attached file
3. try to see the image just uploaded, you will obtain an error.

* Solution:
In BlobBuilder.finish() if blob is compressed and it's size is equal to original version (uncompressed), uncompress it.

et bis

### CODE REVIEW

**Comment by rupalid** [comment]
Looks ok to me.

**Comment by chinmay15** [comment]
This code has compilation errors
```
    [javac]   reason: class file for org.codehaus.jackson.annotate.JsonTypeInfo$Id not found
    [javac] /mnt/hgfs/chinmay.pathak/GitHub/zm-mailbox/store/src/java/com/zimbra/cs/store/BlobBuilder.java:247: error: cannot find symbol
    [javac]                 in = new GZIPInputStream(new FileInputStream(file));
    [javac]                                              ^
    [javac]   symbol:   class FileInputStream
    [javac]   location: class BlobBuilder
    [javac] /mnt/hgfs/chinmay.pathak/GitHub/zm-mailbox/store/src/java/com/zimbra/cs/store/BlobBuilder.java:249: error: cannot find symbol
    [javac]                 IOUtils.copy(in,out);
    [javac]                 ^
    [javac]   symbol:   variable IOUtils
    [javac]   location: class BlobBuilder
    [javac] /mnt/hgfs/chinmay.pathak/GitHub/zm-mailbox/store/src/java/com/zimbra/cs/store/BlobBuilder.java:252: error: cannot find symbol
    [javac]                 IOUtils.closeQuietly(in);
    [javac]                 ^
    [javac]   symbol:   variable IOUtils
    [javac]   location: class BlobBuilder
    [javac] /mnt/hgfs/chinmay.pathak/GitHub/zm-mailbox/store/src/java/com/zimbra/cs/store/BlobBuilder.java:253: error: cannot find symbol
    [javac]                 IOUtils.closeQuietly(out);
    [javac]                 ^
    [javac]   symbol:   variable IOUtils
    [javac]   location: class BlobBuilder
```
imports are missing for GZIPInputStream, IOUtils and FileInputStream classes.

**Comment by Prashantsurana** [comment]
@DinoPuller  please fix and submit pull request again.

**Comment by DinoPuller** [comment]
https://github.com/Zimbra/zm-mailbox/pull/725

**Pull request merged**
