### PR TITLE
Bugfix/zcs 1773

### PR DESCRIPTION
**Pull request by jasonyi-zimbra**
Updated ZimbraPerf.java and ImapDaemon.java to properly intialize ZimbraPerf in ImapDaemon to write out imapd.csv file for ImapDaemon stat collection.

### CODE REVIEW

**Comment by fatkudu** [comment]
What testing has been done?  I assume this needs to work on a node which only has imapd installed as well nodes that also have mailbox installed.

**Comment by jasonyi-zimbra** [comment]
I did a build with feature/imap to do test few weeks ago.  The build wasn't stable with other issues unrelated to what I did.  I, however, did testing via debugger.
If you have to fix/add to unstable branch like feature/imap, how do you go about testing?

**Comment by grishick** [comment]
Current feature/imap builds are stable enough to verify this fix. I suggest adding a SOAP test that triggers some data to be written to imapd.csv and verifies that data was written to imapd.csv.

**Comment by jasonyi-zimbra** [comment]
With the latest feature/imap I was able make a new build and test impad successfully.  It's correctly writing to imapd.csv file.

**Comment by tmclane** [comment]
Please add a soap test that can verify the logging happens.
Otherwise this looks good.

**Comment by jasonyi-zimbra** [comment]
There's no soap call to test for imap, not that I know off.  I tested with actual imap client.  Let me know if I'm missing something about soap.

**Comment by fatkudu** [comment]
What Travis is saying I think is that all changes should have associated automated tests where possible - and how we would typically create tests for this would be to use the RunUnitTestsRequests framework as that requires Zimbra installed, so the right environment will be there.  I imagine there is s steepish learning curve for Jason to write those tests, so it might be better for one of the ZMS team to do that???

**Comment by grishick** [comment]
@fatkudu we can help @jasonyi-zimbra get up to speed with SOAP tests, but otherwise, whoever makes the code change should be adding the test. There is no way around it, so we better help @jasonyi-zimbra get familiar with the test framework sooner.

**Comment by jasonyi-zimbra** [comment]
Do we have any documentation on how to go about creating SOAP test? Is this also a standard across all the zimbra branches, front and backend, including Junit, etc.?

**Comment by fatkudu** [comment]
Most of the tests are in zm-mailbox under **store/src/java/com/zimbra/qa/unittest/** and they are junit tests.  I suggest you add a test file under there.  Perhaps look at recently changed files for a feel of what the latest best practices are.

See http://wiki.eng.zimbra.com/index.php/Zimbra/Building_and_Running_ZCS for some info about installing and building Zimbra - note that the junit jar needs to be copied to the Zimbra installation as mentioned on that page.

To patch in a new store jar, I use this command from the zm-mailbox/store directory

    ant -Dzimbra.buildinfo.version=8.7.11_GA clean deploy publish-local

You can run a test once it is installed as part of the server using, for example:

    zmsoap -z RunUnitTestsRequest/test=com.zimbra.qa.unittest.TestImapViaImapDaemon

To include the test in the list that gets automatically run, edit:

    store/src/java/com/zimbra/qa/unittest/ZimbraSuite.java

**Comment by grishick** [comment]
looks like this PR needs another rebase

**Comment by jasonyi-zimbra** [comment]
I've done the rebase.  As for conflicting files, let me know who has to resolve them.

**Comment by tmclane** [comment]
@jasonyi-zimbra Generally the person doing the rebase does the conflict resolution.
Your changes are small enough you should not have run into any conflicts.
Ping me on hipchat and I'll show you how to avoid the conflicts when doing the rebase.

**Comment by jasonyi-zimbra** [comment]
I did not get any conflict when I rebased, but I see conflicts in git pull request page. 

So as long as I don't see the conflict in rebase, I don't need to worry about the git pull request page with conflicts?

**Comment by tmclane** [comment]
@jasonyi-zimbra You have yet to push your rebased changes back to the branch.
Run the following on the command line: 

    git push <remote> +bugfix/ZCS-1773 

Note: Your remote name is likely 'origin' but if not please use the appropriate name.
           You can check the naming with 'git remote -v' to see which one is your fork which is where you have pushed your branch.

**Comment by jasonyi-zimbra** [comment]
I've pushed to my fork with no issue. 

git push https://github.com/jasonyi-zimbra/zm-mailbox.git +bugfix/ZCS-1773

**Comment by tmclane** [comment]
You apparently are rebasing against a stale version of 'feature/imap'.
Please rerun the rebase after doing a fetch to get the most recent update:

    git fetch git@github.com:Zimbra/zm-mailbox.git feature/imap
    
You can then checkout your copy of 'feature/imap' and reset it to the current or rebase against the remote hash.

Reset:

    git checkout feature/imap
    git reset --hard origin/feature/imap
    git checkout feature/zcs-1773
    git rebase feature/imap

Rebase against remote branch:

    git checkout feature/zcs-1773
    git rebase origin/feature/imap 

Assuming the remote for the Zimbra/zm-mailbox.git is named 'origin'.

**Comment by jasonyi-zimbra** [comment]
I'm getting conflicts from two files that isn't part of my fix. 

Who should resolve the conflicts? 

store\ivy.xml 
store\src\java\com\zimbra\qa\unittest\TestWaitSetRequest.java

**Comment by tmclane** [comment]
As I said before I don't believe you should have any conflicts.
You must be rebasing more commits than you should be:

Please try:

    git rebase --onto origin/feature/imap 14fa448279 bugfix/ZCS-1773

This should only move the commits that you actually need to the end of `origin/feature/imap`

**Comment by jasonyi-zimbra** [comment]
Ok, that worked.  Thank you for your patience, Git is still new to me.

**Comment by tmclane** [comment]
There are still more commits in your PR than I believe are necessary.
It would appear that you included stuff from your earlier attempts at rebasing which duplicated commits. 

I'll push up what I believe your branch should look like after the rebase into my fork.
Please check it out.  I'd like to help you understand what I did and why.

**Comment by jasonyi-zimbra** [comment]
Where do I look for your fork? 





This message and any attachment may contain information that is confidential and/or proprietary. Any use, disclosure, copying, storing, or distribution of this e-mail or any attached file by anyone other than the intended recipient is strictly prohibited. If you have received this message in error, please notify the sender by reply email and delete the message and any attachments. Thank you.

**Comment by tmclane** [comment]
Please view this PR on Github.com as the link I gave previously should provide the easiest view to which commits should be in your PR.

My fork is here: https://github.com/tmclane/zm-mailbox

Note: I believe the command gave invalid results for you because of where your `bugfix/ZCS-1773` branch was located at the time of the `git rebase --onto` command.  If it was at your original hash '33ca93ef8e' you would have gotten identical results except the git hashes would be different because of the rebase operation.

You can redo your operations by doing the following:

    git checkout -b ZCS-1773-original 33ca93ef8e
    git rebase --onto origin/feature/imap 14fa448279 ZCS-1773-original

This should result in same commits shown in the PR that can be created from my fork containing your branch rebased.

**Comment by jasonyi-zimbra** [comment]
I see that ZCS-1773-original is same as yours. 

So how do I fix bugfix/ZCS-1773 ? 






This message and any attachment may contain information that is confidential and/or proprietary. Any use, disclosure, copying, storing, or distribution of this e-mail or any attached file by anyone other than the intended recipient is strictly prohibited. If you have received this message in error, please notify the sender by reply email and delete the message and any attachments. Thank you.

**Comment by tmclane** [comment]
Just push it in.  You will have to add the '+' to force the push since you will be overwriting history on that particular branch.
Please don't use that capability indiscriminately. 

    git push origin +ZCS-1773-original:bugfix/ZCS-1773

**Comment by jasonyi-zimbra** [comment]
do i need to replace "origin" with my branch https://github.com/jasonyi-zimbra/zm-ajax.git ? 

with origin i get permiision error 





This message and any attachment may contain information that is confidential and/or proprietary. Any use, disclosure, copying, storing, or distribution of this e-mail or any attached file by anyone other than the intended recipient is strictly prohibited. If you have received this message in error, please notify the sender by reply email and delete the message and any attachments. Thank you.

**Comment by tmclane** [comment]
Do you see how I got the correct hashes to use in the commands?

I used an alias I have set in my .gitconfig:
    lol = log --graph --decorate --pretty=oneline --abbrev-commit
    lola = log --graph --decorate --pretty=oneline --abbrev-commit --all

These let you see the layout of commits in relation to different branches in the repository.

**Comment by tmclane** [comment]
Yes you do need to update 'origin' with your remote name.
Also you need to use the correct repository as well.
In this case 'zm-mailbox'.

**Comment by jasonyi-zimbra** [comment]
i used the log but got confused. thanks.

**Comment by jasonyi-zimbra** [comment]
Am I to merge this to feature/imap or someone else?

**Comment by grishick** [comment]
@jasonyi-zimbra , I'll merge the PR

**Pull request merged**
