### PR TITLE
Bugfix/zcs 11120: GetAppointmentIdsInRangeRequest soap request not working

### PR DESCRIPTION
**Pull request by shrutig0510**
GetAppointmentIdsInRangeRequest  giving error for soap request.
Fixed issue with transaction before read operation

Also fixed failing soap request GetAppointmentIdsSinceRequest in the same ticket

### CODE REVIEW

**Review by dasiyogesh — APPROVED** [review]

**Comment by abhishekdeshmukh2209** [comment]
Change the pr name with something like 
ZCS-11120: <Description>

**Review by abhishekdeshmukh2209 — COMMENTED** [review]
Change the pr name from Bugfix/zcs 11120  with something like
ZCS-11120: -Description-

**Review by preshitaagrawal — APPROVED** [review]

**Review by abhishekdeshmukh2209 — APPROVED** [review]
LGTM

**Review by zimsuchitgupta — APPROVED** [review]
LGTM

**Pull request merged**
